services:
  nuxt-app:
    # Build the image from the Dockerfile in the current directory
    # and pass in build-time arguments.
    build:
      context: .
      args:
        - POSTCODE_API_TOKEN=${POSTCODE_API_TOKEN}
    # Name of the container
    container_name: nuxt4_app
    # Restart the container automatically if it stops
    restart: unless-stopped
    # This makes the variable available at RUNTIME
    env_file:
      - .env
    # Map port 80 on the host (your VM) to port 3000 in the container
    ports:
      - "80:3000"